version: '3'

services:
  gordias_db:
    image: postgres:10-alpine
    volumes:
      - ./postgres/tables_init.sql:/docker-entrypoint-initdb.d/tables_init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'pg55_2.0'
      POSTGRES_USER: 'gordias1'
      POSTGRES_DB: 'gordias_test'
  gordias_app:
    build: .
    command: python __main__.py
    depends_on:
      - gordias_db
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
    links: 
      - gordias_db:db

volumes:
  postgres_data: